# Generated by Django 6.0.7 on 2026-08-05 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('features', models.JSONField()),
                ('probability', models.FloatField()),
                ('status', models.CharField(choices=[('pending_review', 'En attente de revue'), ('confirmed', 'Attaque confirmee'), ('false_positive', 'Faux positif')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_logs', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'created_at'], name='detection_a_site_id_0bcfb6_idx'), models.Index(fields=['ip'], name='detection_a_ip_64ae2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('protocol_type', models.CharField(blank=True, max_length=10)),
                ('probability', models.FloatField()),
                ('is_attack', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'created_at'], name='detection_c_site_id_d43c65_idx'), models.Index(fields=['ip'], name='detection_c_ip_4c06d6_idx')],
            },
        ),
    ]
